version: "3.3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=games
      - MYSQL_USER=games
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
  
  ui:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - NODE_CONFIG_ENV=docker
      - MYSQL_DATABASE=games
      - MYSQL_USER=games
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: ./config/mysql.txt
  db_root_password:
    file: ./config/mysql_root.txt

volumes:
  db_data:
