version: "3.3"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=games
      - POSTGRES_USER=games
      - POSTGRES_PASSWORD_FILE=/var/run/secrets/db_password
    secrets:
      - db_password
  
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_CONFIG_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=games
      - DB_USER=games
      - DB_PASSWORD_FILE=/var/run/secrets/db_password
    secrets:
      - db_password

  ui:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - api

secrets:
  db_password:
    file: ./config/mysql.txt
