version: "3.3"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=games
      - POSTGRES_USER=games
      - POSTGRES_PASSWORD_FILE=/var/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - /var/lib/docker-volumes/games/postgres/data:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer:4.7.8
    depends_on:
      - db
    ports:
      - "8080:8080"

  api:
    build: ./api
    image: ${REGISTRY}/games/api:0.0.4
    depends_on:
      - db
    environment:
      - NODE_CONFIG_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=games
      - DB_USER=games
      - DB_PASSWORD_FILE=/var/run/secrets/db_password
      - IGDB_ID=${IGDB_ID}
      - IGDB_SECRET_FILE=/var/run/secrets/igdb_secret
    secrets:
      - db_password
      - igdb_secret
    volumes:
      - /var/lib/docker-volumes/games/api:/usr/src/app/src/cache
    configs:
      - source: api_config
        target: /usr/src/app/config/docker.json

  ui:
    build: ./ui
    image: ${REGISTRY}/games/ui:0.0.6
    ports:
      - "80:80"
    depends_on:
      - api

secrets:
  db_password:
    file: ./config/mysql.txt
  igdb_secret:
    external: true

configs:
  api_config:
    file: ./api/config/docker.json
